### ISSUE TITLE
DPY-3016: python-oracledb thin mode cannot be used because the cryptography package is not installed

### ISSUE THREAD

**Issue by Wedge009** [oracle/python-oracledb#100]
Greetings. I'm trying to understand what's going wrong with `oracledb` when it's run from a PyInstaller-packaged executable. While I have no problems running my code through standard Python interpreter, the users expected for the program won't necessarily be, hence the effort to package the code via PyInstaller.

I've isolated the problem to a simple, single-file program that just imports `oracledb` (running current version 1.2.0) and attempts to make a connection to an Oracle database, verifying that it works when run via Python interpreter. Confirming that PyInstaller is including the `cryptography` package, I still get the error message:

```
oracledb.exceptions.NotSupportedError: DPY-3016: python-oracledb thin mode cannot be used because the cryptography package is not installed
```

The stack trace points me to the following:
https://github.com/oracle/python-oracledb/blob/af750c64f90ec68851f953cbf25312e309c6d1f1/src/oracledb/impl/thin/connection.pyx#L70-L74

But I'm not really sure what's involved in the `HAS_CRYPTOGRAPHY` check. Any ideas where I should continue investigation? I'd appreciate some guidance here. Thanks in advance.

**Comment by cjbj** [comment]
Some exisiting issues/discussion question might give clues about packaging with PyInstaller.

And hopefully someone will submit a PR adding some instructions to our doc.....

**Comment by Wedge009** [comment]
> And hopefully someone will submit a PR adding some instructions to our doc.....

Ugh, I was about to submit a PR with e9175becd4dcdb5cbcf262751633c0f02bd3d21f to address your suggestion, but then I saw the requirement to sign agreements, etc. Given that this issue was encountered as part of my employment, I'm not sure I'm in a position to sign any such agreements (this is my personal account that I'm writing from). So alas, I think I will leave this for now.

**Comment by cjbj** [comment]
@Wedge009 I appreciate the intent.  Can you list the instructions clearly here?  Where to use `--hidden-import`, how the .spec file is created etc (if those are the things to be done!)?

**Comment by Wedge009** [comment]
I would expect PyInstaller users would know how to do that already, or at least know where to look for that information in the PyInstaller documentation, which is why I linked to it. I'm no expert, myself, having only used it because that's what a colleague wanted to use to package the code we are working on.

**Comment by adrenaline09** [comment]
Tried creating oracledb layer via AWS Cloudshell and it worked (HUE HUE). Below are the req steps:

Install python 3.9 using the following commands.
$ sudo yum install gcc openssl-devel bzip2-devel libffi-devel
$ cd /usr/src
$ sudo wget https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz
$ sudo tar xzf Python-3.9.7.tgz
$ cd Python-3.9.7 $ ./configure --enable-optimizations
$ sudo make altinstall

Install oracledb and create a zip package.
$ cd
$ mkdir python
$ pip3.9 install --target ./python oracledb
$ zip -r9 oracledb.zip python

Publish zip package as a Lambda layer.
$ aws lambda publish-layer-version --layer-name oracledb-layer --compatible-runtimes python3.9 --zip-file fileb://oracledb.zip
Alternative:- Download the zip file and upload it manually

**Comment by pablobetes** [comment]
I managed to make it work by adding the `--hidden-import` flag to the pyinstaller command as follows:
```shell
python -m pyinstaller myscript.py --hidden-import cryptography.hazmat.primitives.kdf.pbkdf2
```
