### ISSUE TITLE
`outputtypehandler` not respecting `NLS_TERRITORY` in thin mode

### ISSUE THREAD

**Issue by CaselIT** [oracle/python-oracledb#11]
It seems that setting `NLS_TERRITORY ` on the session and using `outputtypehandler` to return floating values to string does not take into consideration that parameter

1. What versions are you using?
```
platform.platform: Windows-10-10.0.19044-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.10.4
oracledb.__version__: 1.0.0
```
I'm using oracle 21.3.0.0, with client version (21, 3, 0, 0, 0)

2. Is it an error or a hang or a crash?

An unexpected result was returned

3. What error(s) or behavior you are seeing?

4. Does your application call init_oracle_client()?

5. Include a runnable Python script that shows the problem.

**Comment by cjbj** [comment]
All NLS environment variables are ignored in Thin mode, see https://python-oracledb.readthedocs.io/en/latest/user_guide/globalization.html

**Comment by anthony-tuininga** [comment]
Take a look at this section in particular: https://python-oracledb.readthedocs.io/en/latest/user_guide/globalization.html#locale-aware-number-and-date-conversions-in-python-oracledb-thin-mode. That will work in both thick and thin modes.

**Comment by CaselIT** [comment]
Not sure why github posted this, I had the new issue open in another tab where I was adding a complete test and all before posting. And I decided to take another look at the doc I found that part.

Sorry for the noise.. closing

**Comment by cjbj** [comment]
@CaselIT I'd love your comments on whether we need to replicate the Oracle globalization support in the Thin driver code to respect some/all NLS environment variables.  Or do the Python solutions work (better)?

**Comment by CaselIT** [comment]
I can't really comment, since I don't really use oracle db for anything other that developing sqlalchemy, and I've otherwise never used globalization on the db side.

This issue was prompted by a test failure in the sqlalchemy test suite and poking at it I found the different behavior between the two modes.

What I can say is that a consistent behavior would be nice, but I understand that it may be a large amount of work for something that may not be very popular/requested (no clue here).

**Comment by cjbj** [comment]
@CaselIT thank you - every comment helps.
