### ISSUE TITLE
pwd.getpwduid(os.getuid()) error on serverless workload

### ISSUE THREAD

**Issue by ArthurQuerido** [oracle/python-oracledb#112]
**1. What versions are you using?**
Python 3.9.10
Platform: Linux-4.14.238-125.422.amzn1.x86_64-x86_64-with-glibc2.26
oracledb 1.2.1
*It's an AWS Glue Python Shell

**2. Is it an error or a hang or a crash?**
Error

**3. What error(s) or behavior you are seeing?**
Get this error when importing the module.

return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 10000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/runscript.py", line 215, in <module>
    handle_errors()
  File "/tmp/runscript.py", line 38, in handle_errors
    raise e_type(e_value).with_traceback(new_stack)
  File "/tmp/glue-python-scripts-GpCK/<\myscripthere>.py", line 3, in <module>
  File "/.pyenv/versions/python39_loaded/lib/python3.9/site-packages/oracledb/__ init __.py", line 38, in <module>

**4. Does your application call init_oracle_client()?**
No. I intend to use just the Thin Mode.

**5. Include a runnable Python script that shows the problem.**
import oracledb 

Ps: I found this problem on a issue from another module, apparently they treated the exception on this call (returning a None) and it was solved. Don't know if you could just do it here but it is worth mentioning.

**Comment by anthony-tuininga** [comment]
I have pushed a patch that should correct this issue. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it corrects your issue as well.

**Comment by anthony-tuininga** [comment]
This patch is included in version 1.2.2 which was just released.
