### ISSUE TITLE
oracledb thin mode: DPY-4000 (Unable to find <DBNAME> in tnsnames.ora

### ISSUE THREAD

**Issue by avmcohen** [oracle/python-oracledb#115]
Hi
While connecting to DB in thin mode, getting the title ERROR (DPY-4000). 
The scenario is only when providing the TNS alias in to dsn argument.
_(ERROR: oracledb.exceptions.DatabaseError: DPY-4000: cannot connect to database. Unable to find "<????>" in /tnsadmin/tnsnames.ora)_ 

When providing full TNS address (IP address:port/DSN) - it connecting fine.
This happened only in thin mode.
In thick mode (and cx_Oracle) it work fine.

**Comment by anthony-tuininga** [comment]
Can you provide the syntax you are using? It looks like you are providing an empty string?

**Comment by anthony-tuininga** [comment]
Interesting! Are you able to share your tnsnames.ora file? You can e-mail it directly to me if you prefer not to share it here.

**Comment by avmcohen** [comment]
Sorry !! You are right.. followed your note I checked the TNS file, and it was corrupted..
few lines before the DB I connected, the **Parenthesis was not closed.**.
Still it's interesting why sqlplus and cx_Oracle easily skipped on corrupted line and found my DB alias.
Thanks a lot !
