### ISSUE TITLE
Thin-Mode XMLTYPE: ORA-01461: can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by avmcohen** [oracle/python-oracledb#116]
The insert failed only In thin mode only:
While fetch and load XML type, which is < 32K, no problem.
with size > 32K, getting the ERROR: ORA-01461: can bind a LONG value only for insert into a LONG column
I used all suggestion:

- getclobval() (convert to CLOB)
- xmltype during insert (with/without)
- set the OutputTypeHandler to convert CLOB to .DB_TYPE_LONG or LONG_STRING

As noted, this worked fine with cx_Oracle and oracledb thick mode

Table:
T ( [columns...] , xml_msg  XMLTYPE)

**Code**:
```python
import oracledb as ora

def OutputTypeHandler(cursor, name, defaultType, size, precision, scale):
    if defaultType == cx_Oracle.DB_TYPE_CLOB:
        return cursor.var(cx_Oracle.DB_TYPE_LONG, arraysize=cursor.arraysize)

sDBS = ora.connect(srcDB)
tDBS = ora.connect(tarDB)

sDBS.outputtypehandler = OutputTypeHandler

sDBC = sDBS.cursor()
tDBC = tDBS.cursor()

sDBC.execute("select <COLS..>, T1.xml_msg.getclobval() from T T1")
db_types = (d[1] for d in sDBC.description)
tDBC.setinputsizes(*db_types)

mDS = sDBC.fetchall()

tDBC.executemany( "insert into T ([Cols..], xml_msg) values ( [Bind Vars..], xmltype(:b_xml_msg) ) , mDS )
```

Thanks

**Comment by patped** [comment]
I just had the same problem and setting input size for the column to `oracledb.CLOB` fixed the problem. In your case if the column is CLOB I think it should be something like this:
`tDBC.setinputsizes(*db_types, xml_msg=ora.CLOB)`

**Comment by avmcohen** [comment]
Excellent ! This worked , Thank you.
Only I could not mix *db_types with keywords (DPY-2005: expecting positional arguments or keyword arguments, not both)
I had to fix it this way:
_db_types = [ ora.CLOB if d[1].name == 'DB_TYPE_LONG' else d[1] for d in sDBC.description]_
then:
_tDBC.setinputsizes(*db_types)_

**Comment by anthony-tuininga** [comment]
In your question you stated:

> As noted, this worked fine with cx_Oracle and oracledb thick mode

I created this table:

```sql
create table issue_116 (
    IntCol          number(9) not null,
    XMLCol          xmltype
);
```

and then ran this Python code:

```python
import oracledb

# oracledb.init_oracle_client()

conn = oracledb.connect("user/password@host/service_name")
cursor = conn.cursor()

data_len = 32768
data = "<value>" + "A" * data_len + "</value>"

# cursor.setinputsizes(None, oracledb.DB_TYPE_CLOB)
cursor.execute("insert into issue_116 values (:1, xmltype(:2))", [1, data])
```

That code fails with both thin and thick -- unless you uncomment the line that sets input sizes. Can you provide a standalone sample that demonstrates the problem that occurs with thin but doesn't with thick? Thanks!

**Comment by avmcohen** [comment]
The following work for me in both thin/think mode - **only with setinputsize**s:
(without it I am getting: _oracledb.exceptions.DatabaseError: ORA-01461: can bind a LONG value only for insert into a LONG column_)

#! /usr/bin/python3
import oracledb as ora # version 1.2.1
#ora.init_oracle_client()
tarDB = "connection String"

#Fetch Data
print ("connecting..")
tDBS = ora.connect(tarDB)
tDBC = tDBS.cursor()

#Tables setup
print ("Generate Data..")
data_len = 32768*100
data = "<value>" + "A" * data_len + "</value>"

#tDBC.setinputsizes( ora.DB_TYPE_CLOB )
#tDBC.setinputsizes( ora.CLOB )

#Load mDS
print ("Load data..")
tINS = "INSERT /*+ APPEND */ INTO XML_116 (xml_msg) values (xmltype(:1))"
print (tINS)

tDBC.executemany(tINS, [(data,)])
print("rollback..")
tDBS.rollback()

**Comment by anthony-tuininga** [comment]
That's what I showed in my example, too. So it sounds like you have answered your question. And it also seems that this is not specific to thin but is also required with thick. I'm going to assume your question is answered, then. If not, feel free to re-open!
