### ISSUE TITLE
oracledb version 1.2.2 cannot be used with pypy

### ISSUE THREAD

**Issue by mscheufe** [oracle/python-oracledb#156]
although a wheel for oracledb can be built, importing oracledb raises the following error:

$ python
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
[PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import oracledb
<frozen importlib._bootstrap>:228: UserWarning: datetime.date size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mscheufe/venvs/test_oracledb_pypy/lib/pypy3.9/site-packages/oracledb/__init__.py", line 38, in <module>
    from .connection import connect, Connection
  File "/home/mscheufe/venvs/test_oracledb_pypy/lib/pypy3.9/site-packages/oracledb/connection.py", line 45, in <module>
    from . import base_impl, thick_impl, thin_impl
  File "src/oracledb/thin_impl.pyx", line 1, in init oracledb.thin_impl
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject

**Comment by cjbj** [comment]
pypy is not an environment we are supporting, though according the [pypy faq](https://doc.pypy.org/en/latest/faq.html#do-c-extension-modules-work-with-pypy) there should have been a good chance it would work out of the box. Maybe python-oracledb is tickling one of the things missing from pypy's C module "support is almost complete" features.

**Comment by cjbj** [comment]
Pull Requests to fix issues are welcome.
