### ISSUE TITLE
How to I connect Django app to OCI Autonomous DB?

### ISSUE THREAD

**Issue by mikekenn** [oracle/python-oracledb#157]
### Discussed in https://github.com/oracle/python-oracledb/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **mikekenn** March  6, 2023</sup>
Im following along in the [Django documentation](https://docs.djangoproject.com/en/4.1/intro/tutorial01/) and I want to connect the application for a Free Tier OCI DB that I have running.

I am able to connect to the DB via VS Code and perform all the expected actions. But I would like it, so that when I do `python manage.py migrate` all the tables get created in the Oracle DB rather than the provided sqlite db. 

I would also like to be able to run packages/procedures from the app as well. Do I still have to create a connection to the database every time I want to do a query/insert/update? Something like this?

```
connection = oracledb.connect(
                              user="USERNAME",
                              password="PASSWORD",
                              dsn="DSN_VALUE_FROM_OCI_CONNECTION_UI",
                              config_dir="/Location/ToApp/Wallet",
                              wallet_location="/Location/ToApp/Wallet",
                              wallet_password=pw)

with connection.cursor() as cursor:

    cursor.execute("""
        begin
            execute immediate 'drop table todoitem';
            exception when others then if sqlcode <> -942 then raise; end if;
        end;""")

    cursor.execute("""
        create table todoitem (
            id number generated always as identity,
            description varchar2(4000),
            creation_ts timestamp with time zone default current_timestamp,
            done number(1,0),
            primary key (id))""")

    print("Table created")
```

I have changed the section in settings.py to the following & I have OracleDB installed

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'NAME_FOUND_IN_ORACLE_CLOUD_UI',
        'USER': 'USERNAME',
        'PASSWORD': 'USER_PASSWORD',
        'HOST': 'Value_In_TNSNAMES.ORA_FILE',
        'PORT': 'Value_In_TNSNAMES.ORA_FILE', 
    }
}
```

Is there something I am missing? Also, I am working on a "3 GHz 6-Core Intel Core i5" desktop & a "Apple M1" laptop. Guidance on how to get this to work on both machines would be greatly appreciated!

Please let me know if there is more information that is required!</div>

**Comment by cjbj** [comment]
@suraj-ora-2020 can you comment?

**Comment by cjbj** [comment]
On second thoughts, lets continue the discussion in the duplicate Discussion https://github.com/oracle/python-oracledb/discussions/155
