### ISSUE TITLE
ConnectParams.set() does not update wallet_location

### ISSUE THREAD

**Issue by theo-fokkinga** [oracle/python-oracledb#163]
1. What versions are you using?
```
platform.platform: Linux-5.4.17-2136.316.7.el7uek.x86_64-x86_64-with-glibc2.17
sys.maxsize > 2**32: True
platform.python_version: 3.9.16
oracledb.__version__: 1.2.2
```

2. Is it an error or a hang or a crash?
Error

3. What error(s) or behavior you are seeing?
After calling `ConnectParams.parse_connect_string()`, some parameters are not updated using `ConnectParams.set()`. For instance: `wallet_location` and `ssl_server_dn_match`.The `user` parameter however does get updated.

```
ora_conn_params = oracledb.ConnectParams()
ora_conn_params.parse_connect_string("(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=example.oracle.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=ORCL)))")
ora_conn_params.set(wallet_location="/home/oracle/wallet")
```

The `oracle_wallet` parameter is still `None`.

4. Does your application call init_oracle_client()?
No, The issue is on the generic object `oracledb.ConnectParams().` No `init_oracle_client()` is called (yet).

6. Include a runnable Python script that shows the problem.
```
import oracledb

username = "scott"
connect_string = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=example.oracle.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=ORCL)))"
wallet_location = "/home/oracle/wallet"


# NOT WORKING - starting with `parse_connect_string`
print("NOT WORKING - starting with `parse_connect_string`")
ora_conn_params = oracledb.ConnectParams()
ora_conn_params.parse_connect_string(connect_string)
ora_conn_params.set(wallet_location=wallet_location)
ora_conn_params.set(ssl_server_dn_match=False)
ora_conn_params.set(user=username)

print(ora_conn_params.get_connect_string())
print(ora_conn_params.user)
print(ora_conn_params.ssl_server_dn_match)
print(ora_conn_params.wallet_location)

ora_conn_params = oracledb.ConnectParams()

print("\nWORKING - starting with `set`")
ora_conn_params.set(wallet_location=wallet_location)
ora_conn_params.set(ssl_server_dn_match=False)
ora_conn_params.set(user=username)
ora_conn_params.parse_connect_string(connect_string)

print(ora_conn_params.get_connect_string())
print(ora_conn_params.user)
print(ora_conn_params.ssl_server_dn_match)
print(ora_conn_params.wallet_location)
```

Output:
```
NOT WORKING - starting with `parse_connect_string`
(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=example.oracle.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=ORCL))(SECURITY=(SSL_SERVER_DN_MATCH=ON)))
scott
True
None

WORKING - starting with `set`
(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=example.oracle.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=ORCL))(SECURITY=(MY_WALLET_DIRECTORY=/home/oracle/wallet)))
scott
False
/home/oracle/wallet
```

**Comment by anthony-tuininga** [comment]
This is not a bug, but expected behavior. The `parse_connect_string()` call will use all of the parameters you set earlier as default values, but subequent `set()` calls will not affect the values that were parsed. The main reason for this is that a parsed connect string could contain *multiple* descriptions and addresses and setting all of them would be undesirable behavior -- at least in some cases! I'm not sure how clear this is in the documentation, so will look and see if clarification can be made there.

**Comment by theo-fokkinga** [comment]
Thanks for your response. For parameters that are actually set or part of the connect string, that would make more sense to me. But the parameters in this case are not part of the connect string and they are not modifiable after the `parse_connect_string()` either.

When looking at the documentation for the `parse_connect_string()`, it states that it will override any current stored values. Apparently this only yields for the parameters that  are actually part of the connect string, as it does not reset currently stored values to default for parameters that are not part of the connect string. So that is a good workaround.

As a workaround is available, improving the documentation on this topic, can be helpful!

**Comment by anthony-tuininga** [comment]
> For parameters that are actually set or part of the connect string, that would make more sense to me.

Both `wallet_location` and `ssl_server_dn_match` are allowed to be part of the connect string. Which parameters were you referring to?

**Comment by cjbj** [comment]
We definitely need more guidance in our doc around this.

**Comment by theo-fokkinga** [comment]
> > For parameters that are actually set or part of the connect string, that would make more sense to me.
> 
> Both `wallet_location` and `ssl_server_dn_match` are allowed to be part of the connect string. Which parameters were you referring to?

I had the false assumption that the security parameter (and therefore wallet_location, etc) was unique in a connect string. But in a multi description connect string using description_list, also multiple security parameters are allowed. So I now see you can't use the `set()` anymore after parsing the connect string.
