### ISSUE TITLE
Adding a function to throw an exception in thin mode when it detects that a named time zone is being used instead of returning invalid data.

### ISSUE THREAD

**Issue by dec04** [oracle/python-oracledb#164]
1. Describe your new request in detail

Adding a function to throw an exception in thin mode when it detects that a named time zone is being used instead of returning invalid data.

All information about this enchancement in [this discussion](https://github.com/oracle/python-oracledb/discussions/131#discussioncomment-5491049)

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

Client PC:

> OS: Windows 10 Corporate LTSC. Version: 10.0.17763, 17763
> python 3.9
> python-oracledb 1.2.2

Server DB:

> LSB Version: :core-4.1-amd64:core-4.1-noarch
> Version Oracle DB: 19.03

**Comment by anthony-tuininga** [comment]
This was implemented in version 1.3.0.
