### ISSUE TITLE
Timeout on CLOB read() for certain tables

### ISSUE THREAD

**Issue by jwlkns** [oracle/python-oracledb#206]
I was asked to post my finding as a bug report, so you can look into the problem further.
[Here](https://stackoverflow.com/questions/76679552/python-oracledb-timeout-makes-program-close-out) is my question for the problem on stackoverflow. It turned out the issue was that *sometimes* the program froze on the `read` part of the returned CLOB object after querying for the ddl of the table. I could not establish a real pattern as to why it only sometimes froze, but *when* it froze, it was always on the same tables.

[This](https://gist.github.com/jwlkns/363978928f5698191783f5c324bb2b1c) is one of the tables that kept freezing up. (I trimmed the column names for the gist)

The fix for it, was not using `read` but instead setting the `oracledb.defaults.fetch_lobs = False` flag and working with the returned strings directly. After that I got no more freezes and crashes.

Additionally, due to adding the `call_timeout`, after the timeout passed, the program would exit without throwing any exception. Without setting a timeout the program would just freeze indefinitely.

1. What versions are you using?
Database: 19c
platform.platform: Windows-10-10.0.19044-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.10.8
oracledb.__version__: 1.3.1

2. Is it an error or a hang or a crash?
It is a hang, which results in a crash if I set `call_timeout` to something other than 0 without throwing a catchable exception 

3. What error(s) or behavior you are seeing?
python-oracle db executes the query and as soon as I start working with the resulting CLOB the program hangs / crashes

4. Does your application call init_oracle_client()?
No

5. Include a runnable Python script that shows the problem.
```
import oracledb

def _get_ddl(dbconnection: oracledb.Connection, table: str, schema: str):
    dbconnection.call_timeout = 2000  # 2 seconds

    try:
        # Add semicolons as terminators for this session
        cursor = dbconnection.cursor()
        cursor.execute("BEGIN\n"
                       "    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);\n"
                       "END;")
        # Query DDL
        cursor.execute(f"SELECT DBMS_METADATA.GET_DDL('TABLE', '{table}') AS DDL FROM DUAL")
        # Program breaks in the read() part here
        ddl = cursor.fetchone()[0].read()

        # Query indeces
        cursor = dbconnection.cursor()
        cursor.execute(f"SELECT DBMS_METADATA.GET_DDL('INDEX', index_name) FROM all_indexes WHERE table_name = '{table}' AND owner = '{schema.upper()}'")
        indeces = list(str(x[0]) for x in cursor.fetchall())

        # Parses the retreived ddl and indeces into custom type
        return ddl + indeces
    except BaseException:
        raise
```

**Comment by cjbj** [comment]
Thank for reporting it.

**Comment by anthony-tuininga** [comment]
I tried the table you provided. I had to guess at what the X values are in order to actually create the table! I did not get a hang and the call timeout worked as expected. If you are able to get it to happen consistently can you provide me the output of the program after setting the environment variable `PYO_DEBUG_PACKETS` to any value? I only need the packets starting with the call to dbms_metadata. The ones before that can be ignored. Thanks!

**Comment by jwlkns** [comment]
Sorry for the extra step you had to go through, it's just I am working for a client, and I'd better be safe than sorry and mask some of the data.  
Anyways, for me, it will not hang every time either. It's more like 30% of the time or something. After setting `PYO_DEBUG_PACKETS=1` I could no longer get the program to get stuck. After ~50 attempts, everything worked fine.

**Comment by anthony-tuininga** [comment]
Closing - no further information provided
