### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_base_impl)

### ISSUE THREAD

**Issue by franciswagner** [oracle/python-oracledb#23]
I am trying to use the connect from oraclebd package, like this:
with oracledb.connect(user=user, password=password, dsn=dsn) as connection:
but I am receiving the following error:

```
from . import base_impl, thick_impl, thin_impl
ImportError: dynamic module does not define module export function (PyInit_base_impl)
python-BaseException
```

**Comment by anthony-tuininga** [comment]
Did you build it yourself? What platform?

**Comment by franciswagner** [comment]
I have installed the 1.01 version with conda.

**Comment by franciswagner** [comment]
I am using MacOS with intel processor.

**Comment by anthony-tuininga** [comment]
Can you try without Conda? Since the base_impl submodule is an extension module, I'm not sure that Conda will be able to handle that properly. I don't know enough about Conda, however, to know what needs to be done to make it happy.

**Comment by cjbj** [comment]
Closing - no update

**Comment by PAFlores** [comment]
Can this discussion be reopened?  Issue is still not resolved, especially for those who are not recompiling the base code or have no option but to use Anaconda.

**Comment by anthony-tuininga** [comment]
Take a look at this [article](https://cjones-oracle.medium.com/python-oracledb-is-now-installable-with-conda-34ebe776d7db). If that doesn't help, open a new issue and explain what you tried and what errors you are getting (with full traceback). Also include version numbers!
