### ISSUE TITLE
Support for passing additional SSL cipher suites for TLS connections

### ISSUE THREAD

**Issue by hvardhan20** [oracle/python-oracledb#259]
1. Describe your new request in detail
Currently, oracledb uses only default cipher suites provided by python's SSLContext to make TLS connections. This limits connectivity to legacy Oracle DBs that use older Cipher suites like SSL_RSA_WITH_AES_256_CBC_SHA(AWS RDS's default cipher) which is not included in python's default security context.
We need a way to pass additional SSL cipher suites for establishing TLS connections. This could be done in multiple ways(Pass SSLContext to connect(), CIPHER_SUITES env var, etc).

2. Give supporting information about tools and operating systems.  Give relevant product version numbers
This enhancement supports DBs using older Cipher suites for TLS.

**Comment by anthony-tuininga** [comment]
I have pushed a patch that should implement this enhancement. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you.

**Comment by hvardhan20** [comment]
> I have pushed a patch that should implement this enhancement. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you.

Works well! Thanks for the quick turn around!

**Comment by anthony-tuininga** [comment]
The patch has been included in version 2.0.0 which was just released.
