### ISSUE TITLE
Unable to manually install oracledb using the zip package

### ISSUE THREAD

**Issue by amiitt** [oracle/python-oracledb#260]
I have downloaded the zip package for oracledb (version 1.4.2).
When I try to install it manually on my Windows 11 machine using `python setup.py install`, I am getting the following error:

`
FileNotFoundError: [Errno 2] No such file or directory: 'src/oracledb/impl/thick/odpi/src'`

On investigating the issue, I found that the mentioned directory is completely empty!

**Comment by cjbj** [comment]
This is mentioned and the solution giving in the doc [Installing from Source Code](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code).
