### ISSUE TITLE
python-oracledb 2.0 has been released with asyncio support

### ISSUE THREAD

**Issue by cjbj** [oracle/python-oracledb#270]
python-oracledb 2.0 is here !

The main changes are:

- Support for asynchronous concurrent coding
- Support for ‘Success With Info’ warnings
- Support for configuring the SDU in Thin mode
- The future `oracledb.__future__.old_json_col_as_obj` has been removed
- New Connection object attributes
- New SQL Domain and Annotation attributes
- Some obsolete, long deprecated parameters like `encoding` and `nencoding` have been desupported
- Support for the obsolete Python 3.6 release has been dropped

Check out the [release announcement blog post ](https://cjones-oracle.medium.com/python-oracledb-2-0-has-asyncio-support-2b913e40f9ca).

Update: we removed the pre-release status from the AsyncIO support in python-oracledb 2.1

**Comment by CaselIT** [comment]
just noticed a typo: connect_async should return a AsyncConnection (I was about to open a PR but it did not seem worth it to create an oracle account to sign the oca just for it)

**Comment by cjbj** [comment]
@CaselIT do you mean the typo "The pool_class parameter is expected to be a [AsyncConnectionPool Object](https://python-oracledb.readthedocs.io/en/latest/api_manual/async_connection_pool.html#asyncconnpoolobj) or a subclass of AsyncConnectionPool." [here](https://python-oracledb.readthedocs.io/en/latest/api_manual/module.html#oracledb.create_pool_async) ?

**Comment by CaselIT** [comment]
No this one: https://github.com/oracle/python-oracledb/blob/9645d4f9b3fb196925ac364e6dec3ab953fca222/src/oracledb/connection.py#L1750

the function `connect_async` returns a `Connection`, but should return an `AsyncConnection`

**Comment by cjbj** [comment]
Thanks. And thanks for the thick-mode error comment.  (I'm glad we called asyncio support a 'pre-release' in this version!) I'll leave these issues to @anthony-tuininga to resolve when he's back online.

**Comment by CaselIT** [comment]
In my case the driver worked fine, it's just the typing that have a typo.
At runtime everything works in my test

**Comment by WolfEYc** [comment]
ok, good to hear, they just need to fix the typing then we are all good!

**Comment by anthony-tuininga** [comment]
I just pushed the corrections to the typing declarations.

**Comment by anthony-tuininga** [comment]
@WolfEYc, the first issue I can take a look at. The second issue, however, is very vague. I am able to make use of an async connection pool without hanging and I don't have to drop/create a connection each time either. Can you file a new issue and provide details of your scenario so that I can look into it further? Thanks!

**Comment by anthony-tuininga** [comment]
This issue is intended as an announcement. Please log any new issues separately instead of commenting here. Thank you!
