### ISSUE TITLE
Question regarding packet information

### ISSUE THREAD

**Issue by charankamarapu** [oracle/python-oracledb#289]
https://github.com/oracle/python-oracledb/blob/4c903a824da5ea3388f4417ab3e71017296b9442/src/oracledb/impl/thin/messages.pyx#L1883

what does line turnaround and value of 1 exactly mean here?

**Comment by anthony-tuininga** [comment]
I believe the line turnaround is an obsolete field and its value is unimportant.

The value of 1 is used to determine whether the client is little endian or big endian. Since the thin client uses the "heterogeneous" mode its value is not important either.

**Comment by cjbj** [comment]
Closing as answered.
