### ISSUE TITLE
Add way to handle DPY-3007: database type "DB_TYPE_INTERVAL_YM" is not supported

### ISSUE THREAD

**Issue by rudyryk** [oracle/python-oracledb#310]
1. Describe your new request in detail

As known and described in the official documentation database type `DB_TYPE_INTERVAL_YM` is [not supported](https://python-oracledb.readthedocs.io/en/latest/api_manual/module.html#oracledb.DB_TYPE_INTERVAL_YM). But what is unclear is how to mitigate this limitation.

For example, when running `SELECT * FROM "MYDB"."SOMETABLE"` an error is thrown:

```DPY-3007: database type "DB_TYPE_INTERVAL_YM" is not supported```

The expected behaviour would be to replace unsupported values with some `UNSUPPORTED` token or just `None`. Otherwise it's becomes impossible to use `SELECT *` in case when it's potentially possible to have unsupported types.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

- Ubuntu 22.04.1 2 x86_64 GNU/Linux
- Python 3.11.5
- oracledb 2.1.0

**Comment by anthony-tuininga** [comment]
It shouldn't be too much effort to add a class specific to this since Python itself doesn't handle it. I'll consider it for 2.2.

**Comment by anthony-tuininga** [comment]
I have added the necessary code to support INTERVAL YEAR TO MONTH as requested. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you, too.

**Comment by anthony-tuininga** [comment]
This was included in version 2.2.0 which was just released.
