### ISSUE TITLE
Conflicting examples in JSON type direct binding

### ISSUE THREAD

**Issue by ryotayamanaka** [oracle/python-oracledb#350]
### What is the link to the documentation section that needs improving?

"Using the Oracle Database 21c JSON Type in python-oracledb" [section](https://github.com/oracle/python-oracledb/blob/main/doc/src/user_guide/json_data_type.rst#using-the-oracle-database-21c-json-type-in-python-oracledb) and its example ([json_direct.py](https://github.com/oracle/python-oracledb/tree/main/samples/json_direct.py)).

- https://github.com/oracle/python-oracledb/blob/c5c6b4f21443b599a458afff933bc4f54734d68f/doc/src/user_guide/json_data_type.rst?plain=1#L69-L71
- https://github.com/oracle/python-oracledb/blob/c5c6b4f21443b599a458afff933bc4f54734d68f/samples/json_blob.py#L65

### Describe the confusion

The following examples are using the dictionary differently.
```
    data = [
      (5, dict(name="Sally", dept="Sales", location="France")),
    ]
...
    cursor.execute(insert_sql, [1, data])
```
```
    data = dict(name="Rod", dept="Sales", location="Germany")
...
    cursor.execute(insert_sql, [1, data])
```

### Suggest changes that would help

I hope to know which is the right way. Thank you.

**Comment by cjbj** [comment]
Thanks for reporting the concern.

Use the examples in  https://github.com/oracle/python-oracledb/tree/main/samples because they run.  Which file and code path to use depends on your table definition and your DB version (and the client version, if you are using Thick mode).

We'll fix the documentation code snippet.

**Comment by cjbj** [comment]
This was fixed in https://github.com/oracle/python-oracledb/commit/d607ef906e9a61e0fd22753100a6e537438faff3
