### ISSUE TITLE
[12568] Failed to execute script 'oracle' due to unhandled exception!

### ISSUE THREAD

**Issue by flowerwOw0316** [oracle/python-oracledb#364]
oracle.py code:

import oracledb
connection = oracledb.connect(
    user="system",
    password="123456",
    dsn="localhost/FREE",
    port=1521)

print("Successfully connected to Oracle Database")

cursor = connection.cursor()

cursor.execute("""
SELECT * FROM VIEW_EXAM_APPLY_SCHEDULE_XSB
        """)

connection.commit()

print(cursor.fetchone())

-------------------------
pyinstaller.exe -F -i .\icon.ico .\oracle.py
-------------------------
![QQ_1721223418283](https://github.com/user-attachments/assets/e768f038-ea39-453c-899c-5b23a5139944)
-------------------------
![QQ_1721223444405](https://github.com/user-attachments/assets/e571d11d-7503-4e0d-a459-0ab26b6ad9bb)
-------------------------
warn-oracle.txt

This file lists modules PyInstaller was not able to find. This does not
necessarily mean this module is required for running your program. Python and
Python 3rd-party packages include a lot of conditional or optional modules. For
example the module 'ntpath' only exists on Windows, whereas the module
'posixpath' only exists on Posix systems.

Types if import:
* top-level: imported at the top-level - look at these first
* conditional: imported within an if-statement
* delayed: imported within a function
* optional: imported within a try-except-statement

IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
            tracking down the missing module yourself. Thanks!

missing module named 'org.python' - imported by copy (optional)
missing module named grp - imported by shutil (optional), tarfile (optional), pathlib (delayed)
missing module named pwd - imported by posixpath (delayed, conditional), shutil (optional), tarfile (optional), pathlib (delayed, conditional, optional)
missing module named org - imported by pickle (optional)
missing module named posix - imported by os (conditional, optional), shutil (conditional), importlib._bootstrap_external (conditional)
missing module named resource - imported by posix (top-level)
missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional)
excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional)
missing module named _posixsubprocess - imported by subprocess (optional)
missing module named bcrypt - imported by cryptography.hazmat.primitives.serialization.ssh (optional)
missing module named oracledb.__name__ - imported by oracledb (top-level), oracledb.defaults (top-level), oracledb.connection (top-level), oracledb.cursor (top-level), oracledb.fetch_info (top-level), oracledb.dbobject (top-level), oracledb.lob (top-level)

**Comment by flowerwOw0316** [comment]
RUN IN IDE
![QQ_1721223546649](https://github.com/user-attachments/assets/8f036572-db45-42a8-b3c4-832d14278ca7)

**Comment by anthony-tuininga** [comment]
The first error shows that you are missing the `decimal` module. There are other modules that are required for oracledb to run properly. You can find out which by looking at the Cython files:

https://github.com/oracle/python-oracledb/blob/main/src/oracledb/base_impl.pyx#L46-L56
https://github.com/oracle/python-oracledb/blob/main/src/oracledb/thin_impl.pyx#L44-L64
https://github.com/oracle/python-oracledb/blob/main/src/oracledb/thick_impl.pyx#L38-L40


Most of those are built-in modules. The `datetime` module is also required. If you are using thin mode the cryptography package is also needed. Hope that helps you!
