### ISSUE TITLE
How to load byte data?

### ISSUE THREAD

**Issue by inhoYoo** [oracle/python-oracledb#378]
hello.
I am in a situation where I want to retrieve data as bytes while using oracledb to connect to DB in Python and load data.

query execution results
This is a situation where you want to retrieve data with unencoded bytes from the part that is automatically encoded to receive with fetchall().

How can I solve this?

thank you

**Comment by cjbj** [comment]
See the answer in your other post https://github.com/oracle/python-oracledb/issues/377

**Comment by inhoYoo** [comment]
> See the answer in your other post #377

Thank you for your reply.

When decoding utf-8, the bytes come out strangely due to incorrect encoding.

b'816\xef\xbf\xbd\xef\xbf\xbd3314' This is actually '816로3314' in Korean, but when I checked the encoding, it showed that it was a broken value due to a conversion error.

What should I do in times like this?
