### ISSUE TITLE
Code error in docs

### ISSUE THREAD

**Issue by imba-tjd** [oracle/python-oracledb#38]
1. What is the link to the documentation section that needs improving?

https://python-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html

2. Describe the confusion

```py
dsn = f'{username}/{userpwd}@{port}:{host}/{service_name}'
```

3. Suggest changes that would help

```
dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
```

**Comment by anthony-tuininga** [comment]
Thanks for reporting that! I'll have that corrected immediately.
