### ISSUE TITLE
Oracledb 2.4.0 connection error: DPY-3008: unsupported in-band notification with error number 12572

### ISSUE THREAD

**Issue by ml-huber** [oracle/python-oracledb#383]
1. What versions are you using?
I am having this problem since oracledb 2.4.0. Version 2.3.0 works like a charm.
platform.platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
sys.maxsize > 2**32: True
platform.python_version: 3.10.12
oracledb.__version__: 2.4.0

2. Is it an error or a hang or a crash?
Error
3. What error(s) or behavior you are seeing?
OperationalError: DPY-6005: cannot connect to database (CONNECTION_ID=...).
DPY-3008: unsupported in-band notification with error number 12572
in line:
oracledb.connect(user=user, password=password, dsn=dsn_str)

4. Does your application call init_oracle_client()?
no, i am using the thin client version

5. Include a runnable Python script that shows the problem.
oracledb.connect(user=user, password=password, dsn=dsn_str)

**Comment by anthony-tuininga** [comment]
That is interesting! Please include a full traceback. From what you are describing, however, it seems that an in-band notification is coming *during* the connect phase. I've never seen that happen before! I'll ask internally to see if there is a way to replicate that.

**Comment by ml-huber** [comment]
Thanks for the quick response. Here is the full traceback:

`OperationalError: DPY-6005: cannot connect to database (CONNECTION_ID=REDACTED).
DPY-3008: unsupported in-band notification with error number 12572
---------------------------------------------------------------------------
NotSupportedError                         Traceback (most recent call last)
File src/oracledb/impl/thin/connection.pyx:322, in oracledb.thin_impl.ThinConnImpl._connect_with_address()

File src/oracledb/impl/thin/protocol.pyx:235, in oracledb.thin_impl.Protocol._connect_phase_one()

File src/oracledb/impl/thin/connection.pyx:115, in oracledb.thin_impl.BaseThinConnImpl._create_message()

File src/oracledb/impl/thin/messages.pyx:85, in oracledb.thin_impl.Message._initialize()

File src/oracledb/impl/thin/packet.pyx:229, in oracledb.thin_impl.ReadBuffer._check_connected()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/oracledb/errors.py:195, in _raise_err(error_num, context_error_message, cause, **args)
    194 error = _create_err(error_num, context_error_message, cause, **args)
--> 195 raise error.exc_type(error) from cause

NotSupportedError: DPY-3008: unsupported in-band notification with error number 12572

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
File ~/.ipykernel/2047/command--1-4018924967:8
      5 del sys
      7 with open(filename, "rb") as f:
----> 8   exec(compile(f.read(), filename, 'exec'))

File /Workspace/Users/REDACTED/.bundle/app/prod/files/main.py:140
    139 if __name__ == '__main__':
--> 140     run()

File /Workspace/Users/REDACTED/.bundle/app/prod/files/main.py:121, in run()
    117 def run():
    118     logging.basicConfig(level=logging.INFO,
    119                         stream=sys.stdout,
    120                         format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
--> 121     all_active_apps_with_desc = combine_desc_with_all_active_apps(get_all_active_apps())

File /Workspace/Users/REDACTED/.bundle/app/prod/files/main.py:20, in get_all_active_apps()
     19 def get_all_active_apps() -> list:
---> 20     with oracle_connection(CONFIG.SCHEMANAME) as connection:
     21         cursor = connection.cursor()
     22         try:

File /Workspace/Users/REDACTED/.bundle/app/prod/files/db_connector.py:18, in oracle_connection(user)
     15 os.environ["NLS_LANG"] = CONFIG.NLS_LANG
     17 dsn_str = f"{CONFIG.HOST}:{CONFIG.PORT}/{CONFIG.SERVICE_NAME}"
---> 18 return oracledb.connect(user=user, password=password, dsn=dsn_str)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/oracledb/connection.py:1169, in _connection_factory.<locals>.connect(dsn, pool, conn_class, params, **kwargs)
   1167     message = "pool must be an instance of oracledb.ConnectionPool"
   1168     raise TypeError(message)
-> 1169 return conn_class(dsn=dsn, pool=pool, params=params, **kwargs)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/oracledb/connection.py:551, in Connection.__init__(self, dsn, pool, params, **kwargs)
    549     else:
    550         impl = thin_impl.ThinConnImpl(dsn, params_impl)
--> 551         impl.connect(params_impl)
    552 else:
    553     impl = thick_impl.ThickConnImpl(dsn, params_impl)

File src/oracledb/impl/thin/connection.pyx:424, in oracledb.thin_impl.ThinConnImpl.connect()

File src/oracledb/impl/thin/connection.pyx:420, in oracledb.thin_impl.ThinConnImpl.connect()

File src/oracledb/impl/thin/connection.pyx:380, in oracledb.thin_impl.ThinConnImpl._connect_with_params()

File src/oracledb/impl/thin/connection.pyx:361, in oracledb.thin_impl.ThinConnImpl._connect_with_description()

File src/oracledb/impl/thin/connection.pyx:327, in oracledb.thin_impl.ThinConnImpl._connect_with_address()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/oracledb/errors.py:195, in _raise_err(error_num, context_error_message, cause, **args)
    190 """
    191 Raises a driver specific exception from the specified error number and
    192 supplied arguments.
    193 """
    194 error = _create_err(error_num, context_error_message, cause, **args)
--> 195 raise error.exc_type(error) from cause

OperationalError: DPY-6005: cannot connect to database (CONNECTION_ID=REDACTED).
DPY-3008: unsupported in-band notification with error number 12572
`

**Comment by ranjeetahlawat** [comment]
getting same error in 2.4.0, version 2.3.0 working fine..  
File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/oracledb/errors.py", line 195, in _raise_err
    raise error.exc_type(error) from cause
oracledb.exceptions.NotSupportedError: DPY-3008: unsupported in-band notification with error number 12572

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.ipykernel/2003/command-25566006827418-4004101905", line 6, in f_run_task
  File "/root/.ipykernel/2003/command-25566006827417-3355304178", line 126, in f_load_oracle_uc_objects
  File "/root/.ipykernel/2003/command-1155521501317754-370638649", line 22, in fc_run_query_on_oracle_db
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/oracledb/connection.py", line 1169, in connect
    return conn_class(dsn=dsn, pool=pool, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/oracledb/connection.py", line 551, in __init__
    impl.connect(params_impl)

**Comment by anthony-tuininga** [comment]
What version of the database are you using? Is the service being drained when you attempt to connect to it? Are you using RAC?

**Comment by anthony-tuininga** [comment]
I have pushed a patch that should correct this issue. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you, too.

**Comment by cepedus** [comment]
Issue present with 19c Entreprise Edition too

**Comment by ml-huber** [comment]
the patch and building it from source works for me, thank you!

**Comment by cepedus** [comment]
In the meantime, is it possible to yank 2.4.0 from pypi? As any install (by default, latest) will be bugged and unusable if `connect(...)` fails

**Comment by latzelth** [comment]
I tested it a bit and found the following outcomes:
instant client always version 19.3
thick mode is always working for me
thin mode works for db version 19.20 but not for 19.17

so for me it seems that the behaviour of the db server also changed in the meantime.

**Comment by anthony-tuininga** [comment]
> In the meantime, is it possible to yank 2.4.0 from pypi? As any install (by default, latest) will be bugged and unusable if connect(...) fails

I plan to push out version 2.4.1 later on today. I don't think it is unusable by most people, but for a few it appears to be!

**Comment by anthony-tuininga** [comment]
This was included in version 2.4.1 which was just released.
