### ISSUE TITLE
register_protocol() in the "latest" documentation despite 2.5 apparently being unreleased

### ISSUE THREAD

**Issue by Evan0000000000** [oracle/python-oracledb#387]
1. What is the link to the documentation section that needs improving?
https://python-oracledb.readthedocs.io/en/latest/api_manual/module.html#oracledb.register_protocol

2. Describe the confusion
This item describes a feature added in version 2.5, however 2.4.1 appears to be the latest release

3. Suggest changes that would help
While it seems from the release notes that 2.5 is complete (or complete enough to have release notes in any case) I would expect "latest" documentation to only reflect released code.

Of course if I somehow happened to catch the documentation and codebase in a state of flux feel free to ignore me :)

**Comment by anthony-tuininga** [comment]
First, 2.5 is still in progress, which is shown by the TBD in the [release notes](https://python-oracledb.readthedocs.io/en/latest/release_notes.html#oracledb-2-5-0-tbd). Second, the only way to avoid having new documentation published is to either exclude it from the repository, or turn off the automatic building of the documentation when commits are made -- both options are undesirable, I think! If you are intereted in looking only at released code, you can use the version button at the bottom left of the page to select the version of interest.

**Comment by cjbj** [comment]
We understand the concerns.  We know there are pros & cons.  At the moment there are no plans to change the process but will keep it in mind.  I'll close this issue.  Thanks for using python-oracledb and taking the time to raise the point.
