### ISSUE TITLE
Worth mentioning in docs that DPY-6000 with ORA-12660 can be caused by server having NNE enabled?

### ISSUE THREAD

**Issue by matt-hoskins** [oracle/python-oracledb#40]
1. What is the link to the documentation section that needs improving?

https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_b.html#native-network-encryption-and-checksumming

2. Describe the confusion

I was wondering if it might be worth citing the specific error someone would get raised if they try make a thin connection to a server with NNE enabled - I believe it's DPY-6000 with ORA-12660 mentioned. 

I'm currently testing an OCI Oracle Base Database server for replacing an on-premises one and was baffled initially that thin client connections weren't working, when I'd had them behave fine in my on-premises environment, but if I enabled thick mode the connection would work fine. 

The error message I was seeing was:
```
oracledb.exceptions.OperationalError: DPY-6000: cannot connect to database. Listener refused connection. (Similar to ORA-12660)
```

Which initially made me wonder if I was getting the connection string wrong, but checking the tnslistener logs I could see the connection was being made. Googling for DPY-6000 didn't find me anything useful (there is another issue which mentions it, but has a different ORA mentioned), but on googling ORA-12660 I saw that it relates to crypto/encryption.

I then found that the sqlnet.ora set up automatically for the OCI Oracle Base Database service seems to have NNE enabled. A bit more digging in the oracledb docs and I found that documentation section mentioning that thin doesn't support NNE. 

3. Suggest changes that would help

Assuming I'm correct that a raised DPY-6000 citing ORA-12660 is related to the server rejecting the thin client connection where NNE is enabled when the thin client can't handle it, then as per above I wondered if it worth a quick mention in the oracledb docs just so if someone does get that error then googling it/searching the docs will help them more quickly figure out the issue :). It feels like it might be one of the more common things people might bump into and not realise about (if they haven't configured the encryption settings on the server themselves).

But of course I don't mind at all if you'd rather not add anything to docs (at least with this issue existing now I've created it, even if marked don't fix, there's some sort of pointer mention ORA-12660 :) ).

**Comment by anthony-tuininga** [comment]
You are correct in that if the server *requires* NNE that you get ORA-12660. Simply enabling it on the server doesn't cause the error, though. It must be marked as ``REQUIRED``. I'll let @cjbj decide on whether or not to include that reference in the documentation, but I suspect he will agree with your assessment. :-)

**Comment by matt-hoskins** [comment]
Ah, yeah - the OCI Oracle Base Database service servers are indeed set up such that NNE is required. And it's totally understandable why Oracle would configure encryption as required by default on cloud-hosted servers.

Just FYI this is the sqlnet.ora that gets set up:
```
ENCRYPTION_WALLET_LOCATION=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/opt/oracle/dcs/commonstore/wallets/tde/$ORACLE_UNQNAME)))

SQLNET.ENCRYPTION_SERVER=REQUIRED
SQLNET.CRYPTO_CHECKSUM_SERVER=REQUIRED
SQLNET.ENCRYPTION_TYPES_SERVER=(AES256,AES192,AES128)
SQLNET.CRYPTO_CHECKSUM_TYPES_SERVER=(SHA1)
SQLNET.ENCRYPTION_CLIENT=REQUIRED
SQLNET.CRYPTO_CHECKSUM_CLIENT=REQUIRED
SQLNET.ENCRYPTION_TYPES_CLIENT=(AES256,AES192,AES128)
SQLNET.CRYPTO_CHECKSUM_TYPES_CLIENT=(SHA1)
SQLNET.EXPIRE_TIME=10

```

**Comment by cjbj** [comment]
@priyankanair8 this is for you :)

**Comment by anthony-tuininga** [comment]
This has now been done, as you can see [here](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_b.html#native-network-encryption-and-checksumming).
