### ISSUE TITLE
how to query by vector?   demo only show to insert vector.

### ISSUE THREAD

**Issue by ovjust** [oracle/python-oracledb#403]
as to the title.

**Comment by cjbj** [comment]
- https://github.com/oracle/python-oracledb/tree/main/samples
- https://python-oracledb.readthedocs.io/en/latest/user_guide/vector_data_type.html
- https://download.oracle.com/ocomdocs/global/python-oracledb_Vector_Technical_Brief_Oracle_Database_23ai.pdf

**Comment by ovjust** [comment]
i know it, now.
  -- 成功
    SELECT name,VECTOR_DISTANCE(v,(SELECT v FROM genvec WHERE name='C'||'5'),EUCLIDEAN)
  FROM genvec
   where VECTOR_DISTANCE(v,(SELECT v FROM genvec WHERE name='C'||'5'),EUCLIDEAN)<1
  ORDER BY VECTOR_DISTANCE(v,(SELECT v FROM genvec WHERE name='C'||'5'),EUCLIDEAN)

**Comment by cjbj** [comment]
For other readers, a good reference is:

- https://docs.oracle.com/en/database/oracle/oracle-database/23/vecse/overview-ai-vector-search.html
