### ISSUE TITLE
Detect, undo, and forget setinputsizes() on cursor

### ISSUE THREAD

**Issue by deonav** [oracle/python-oracledb#411]
If `setinputsizes` is _**not**_ called, then one can reuse the cursor for different SQL statements without problems like so
```
cur.execute("select :a, :b from dual", a="foo", b="bar")
cur.execute("select :c from dual", c=999)
```
If it _**is**_ called, however, then an exception may be raised. Consider
```
cur.execute("select :a, :b from dual", a="foo", b="bar")
cur.setinputsizes(**cur.bindvars)
cur.execute("select :c from dual", c=999)

>> DPY-4008: no bind placeholder named ":a" was found in the SQL text
```

There doesn't appear to be any way to undo this, for example
```
cur.execute("select :a, :b from dual", a="foo", b="bar")
cur.setinputsizes(**cur.bindvars)

# attempt to reset
cur.setinputsizes()

cur.execute("select :c from dual", c=999)

>> DPY-4008: no bind placeholder named ":a" was found in the SQL text
```

If we could detect if `setinputsizes` were called, and if the empty call `setinputsizes()` would have it forget, then we could safely reuse cursors in procedural programming, such as
```
def foo(cur):
    if cur.inputsizes_called:
        oldvars = cur.bindvars.copy()
        cur.setinputsizes() # reset
        cur.execute(...)
        if isinstance(oldvars, list): 
            cur.setinputsizes(*oldvars) # restore
        elif isinstance(oldvars, dict): 
            cur.setinputsizes(**oldvars)
    else:
        cur.execute(...)
```
Alternatively, the cursor could detect if a different sql statement (string id) were used and then forget on its own.

**Comment by cjbj** [comment]
@deonav thanks for the suggestions.

**Comment by anthony-tuininga** [comment]
I have pushed a patch that adds the requested support and have initated a [build](https://github.com/oracle/python-oracledb/actions/runs/11492064227) from which you can download pre-built development wheels once it completes. You can also [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) if you prefer.
