### ISSUE TITLE
DPY-4011 can be triggered by OOB messaging, not just needing NNE

### ISSUE THREAD

**Issue by lunalucadou** [oracle/python-oracledb#419]
1. What is the link to the documentation section that needs improving?

https://python-oracledb.readthedocs.io/en/latest/user_guide/troubleshooting.html#dpy-4011

2. Describe the confusion

This error says the only cause is having NNE enabled (and thus requiring the thick client), but it can also occur under the following circumstances:

* The Oracle server supports TLS and NNE and is running in a Docker container or otherwise on a platform/behind a firewall that [does not support out-of-band break messages](https://franckpachot.medium.com/19c-instant-client-and-docker-1566630ab20e#e212)
  * NNE support may not be required, all I know for sure is that my environment has both TLS and NNE support
* The server's sqlnet.ora file has `DISABLE_OOB_AUTO=TRUE` (so no OOB test is performed upon client connect which would return ORA-12637), but does not set `DISABLE_OOB=on` to disable OOB altogether (so it's still possible for clients to attempt it)
* The client connects and seems to work fine until it does something that causes an out-of-band message to be sent, resulting in the connection failing and DPY-4011 appearing in the logs

3. Suggest changes that would help

Mention that DPY-4011 can also occur, even for established TLS connections, if OOB messaging is attempted in an environment that lacks OOB support (such as Docker) but whose Oracle server has not fully disabled it.

The server-side solution would be to set [DISABLE_OOB](https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/parameters-for-the-sqlnet.ora.html#GUID-42E939DC-EF37-49A0-B4F0-14158F0E55FD) in the sqlnet.ora file, but setting the `disable_oob=True` [connection option](https://python-oracledb.readthedocs.io/en/latest/api_manual/module.html#oracledb.connect) can also mitigate it on the client side.

**Comment by cjbj** [comment]
Thanks.  I can see the error does get used in a couple of places.

You mention the solution: did this work for you?

**Comment by anthony-tuininga** [comment]
I have pushed a patch that tells the thin driver to pay attention to the `DISABLE_OOB_AUTO` flag when set on the server and have initated a [build](https://github.com/oracle/python-oracledb/actions/runs/11829776618) from which you can download pre-built development wheels once it completes. You can also [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) if you prefer. This won't have much effect on your situation, I believe, but it closes a (small) hole.

**Comment by lunalucadou** [comment]
Sorry for the late reply

> Yet you are saying that TLS is used and OOB is attempted? Can you clarify?

I got an unrelated issue confused; we don't setup any certs in our container (since it's just for testing purposes), so the traffic which triggers this should be unencrypted (we don't configure any encryption-related settings in the sqlnet.ora file).

Technically I don't know for sure it's OOB that is causing it, but it's the only thing I can think of (and would seem to match what I've read about Docker networking), and disabling OOB at the connection level seems to have fixed it.

If there are any debug flags I should try to help narrow things down further, let me know.

**Comment by cjbj** [comment]
@lunalucadou it would be great if you could check the behavior with a development package from https://github.com/oracle/python-oracledb/actions/runs/11829776618/artifacts/2185970208 ?

**Comment by anthony-tuininga** [comment]
The patch has been included in version 2.5.1 which was just released.
