### ISSUE TITLE
Segfault on trying to init oracledb

### ISSUE THREAD

**Issue by jsa34** [oracle/python-oracledb#430]
After a few times running my test suite using pytest, I get a segfault.  I have tried all sorts to remedy:
* different python interpreter versions
* reinstalling venv
* reinstalling InstantClient
but nothing seems to work apart from keep trying.  It happens well over half of the attempts to run the script.

When I restart my computer, it's fine for a few runs again, then I will hit the segfaults, and once they start they are consistent.

It seems to be when it tries to init the client.

I'm using the thick mode and attached segfault and backtrace for reference.

Any help much appreciated as I'm stuck with no way forward!

-------------

1. What versions are you using?
  * InstantClient: 23.3.0.23.09-1
  * oracledb 2.5.0
  * database version: 19.25.0.0.0

```
platform.platform: macOS-15.1.1-arm64-arm-64bit-Mach-O
sys.maxsize > 2**32: True
platform.python_version: 3.13.0
oracledb.__version__: 2.5.0
```

3. Is it an error or a hang or a crash?
Crash

4. What error(s) or behavior you are seeing?
See attached logs

[oracledb-backtrace.txt](https://github.com/user-attachments/files/18042284/oracledb-backtrace.txt)
[oracledb-segfault.txt](https://github.com/user-attachments/files/18042285/oracledb-segfault.txt)

Command ran:
```
pytest -s -m test-tag
```

5. Does your application call init_oracle_client()?

Yes:
oracledb.init_oracle_client(lib_dir=os.getenv("INSTANT_CLIENT_LIB_DIR"))

6. Include a runnable Python script that shows the problem.

```
import oracledb

@pytest.fixture(scope="module")
def db_connection_pool() -> oracledb.ConnectionPool:
    """
    Fixture to create and manage an Oracle database connection pool for the test session.
    It initialises the Oracle client, creates a connection pool, and closes the pool after the session ends.

    Yields:
        oracledb.ConnectionPool: The Oracle database connection pool.
    """
    LOGGER.debug("Starting DB client...")
    oracledb.init_oracle_client(lib_dir=os.getenv("INSTANT_CLIENT_LIB_DIR"))
    LOGGER.debug("Found and started DB client!")

    LOGGER.debug("Starting DB connection pool...")
    pool = oracledb.create_pool(
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        service_name=os.getenv("DB_SERVICE"),
        min=1,
        max=3,
        stmtcachesize=0,
    )
    LOGGER.debug("Pool created!")
    yield pool
    pool.close()
    LOGGER.debug("Pool closed!")


def test_test(db_connection_pool):
     print("test")
```

**Comment by cjbj** [comment]
I wonder if 15.1 has borked something needed by Instant Client, which hasn't been tested on 15.1 AFAIK.  Apple has broken Instant Client in the past so it wouldn't surprise me.  Do other tools like SQL*Plus run?

I haven't upgraded to 15 yet.

**Comment by jsa34** [comment]
Good question - I'll take a look as I only use the instant client for the automated tests.

Interestingly, if I wait or keep trying, I can get the scripts to run without encountering the issue, which makes me suspect something is holding a resource and it has to wait for release that wasn't released.

**Comment by jsa34** [comment]
Just checked, and SQL*Plus is fine

**Comment by anthony-tuininga** [comment]
Do you need to use thick mode? Can you try with version 2.4.1 and version 2.5.1 (just released)? It seems, however, that this is a bug in the instant client libraries and not something we can address directly, unfortunately. If one of those two versions work, however, that would be enlightening.

**Comment by jsa34** [comment]
Unfortunately due to the networking used by the DB, we do have to use thick mode currently :(

I will try now with 2.5.1.  I know 2.4.1 was problematic, too, as I encountered the issue with 2.4.1 and tried upgrading to 2.5.0 to see if it would be fixed.

**Comment by cjbj** [comment]
I didn't have any issue on macOS 15.2 with Python 3.9 and Instant Client 23.3.  I was able to connect to a DB.

**Comment by jsa34** [comment]
Ran a few times and no segfaults as of yet since upgrading to 2.5.1, but this was an issue that didn't occur straight away, so will leave a couple of days and then close if it doesn't occur again, if that's ok?

**Comment by jsa34** [comment]
Closing as no more crashes appeared since upgrading as of yet
