### ISSUE TITLE
Oracle Connectivity is getting hanged

### ISSUE THREAD

**Issue by Gobi2511** [oracle/python-oracledb#434]
When we try to connect oracle at first attempt it is getting stalling when receiving the packet. If we kill the process and re-run it again then the request is completing.

1. What versions are you using?
We are not using instant client libraries. 
- oracledb: 2.5.1
- database version: 19.25.0.0.0

2. Is it an error or a hang or a crash?
It is a Hang. 

3. What error(s) or behavior you are seeing?
This is happening at first time or when there is a delay between the script run, the request is getting hanged. I have interuppted the hanged request manually to get the log where it is getting hanged. Below is the details:

```
File "/home/ubuntu/inside-private-instance/oracle-te.py", line 14, in <module>
    conn = oracledb.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/oracledb/connection.py", line 1134, in connect
    return conn_class(dsn=dsn, pool=pool, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/oracledb/connection.py", line 523, in __init__
    impl.connect(params_impl)
  File "src/oracledb/impl/thin/connection.pyx", line 449, in oracledb.thin_impl.ThinConnImpl.connect
  File "src/oracledb/impl/thin/connection.pyx", line 445, in oracledb.thin_impl.ThinConnImpl.connect
  File "src/oracledb/impl/thin/connection.pyx", line 411, in oracledb.thin_impl.ThinConnImpl._connect_with_params
  File "src/oracledb/impl/thin/connection.pyx", line 392, in oracledb.thin_impl.ThinConnImpl._connect_with_description
  File "src/oracledb/impl/thin/connection.pyx", line 365, in oracledb.thin_impl.ThinConnImpl._connect_with_address
  File "src/oracledb/impl/thin/protocol.pyx", line 289, in oracledb.thin_impl.Protocol._connect_phase_two
  File "src/oracledb/impl/thin/protocol.pyx", line 364, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 436, in oracledb.thin_impl.Protocol._receive_packet
  File "src/oracledb/impl/thin/packet.pyx", line 588, in oracledb.thin_impl.ReadBuffer.wait_for_packets_sync
  File "src/oracledb/impl/thin/transport.pyx", line 300, in oracledb.thin_impl.Transport.read_packet
  KeyboardInterrupt -> We interuppted to get the log.
```

4. Does your application call init_oracle_client()?
Yes. We are using Thin mode. We tried without init_oracle_client method call as well. But nothing helped.

5. Include a runnable Python script that shows the problem.

```
import oracledb

host_name = "xxxxx"
port = 1526
sid = "xxxxx"
user = "xxxxx"
password = "xxxxx"

oracledb.init_oracle_client() # Irrespective of this line it is getting stalled when it hits the next line.
conn = oracledb.connect(
        user = user,
        password = password,
        host = host_name,
        port=port,
        sid=sid
 )

with conn.cursor() as cursor:
    cursor.execute(f"""SELECT NAME FROM V$DATABASE""")
    rows = cursor.fetchall()
    for row in rows:
        print(row)
```

**Comment by rejeeshdqlabs** [comment]
Was stuck with the same issue. Any solution would be very helpful.

**Comment by anthony-tuininga** [comment]
Hmm, I can't replicate the issue with the just released packages. Everything works as expected. The line numbers in the traceback you provided don't match the line numbers in the source -- which suggests you might be running a different version? Can you set the environment variable `PYO_DEBUG_PACKETS` to any value and run the code again and share the results? Can you also try using `service_name` instead of `sid`?

**Comment by cjbj** [comment]
@Gobi2511 @rejeeshdqlabs @govindbose did a previous version connect for you?

**Comment by NikhilShuklaDQLabs** [comment]
This issue is a pain for me and my company. I have spent hours on this without any success.Hopefully we get a solution for this so that i get some peace of mind.

**Comment by cjbj** [comment]
@NikhilShuklaDQLabs solution for what scenario?  Details matter?  Did it occur with an older version?  If not then which version?  As a workaround you can install that version using normal pip commands.

**Comment by Gobi2511** [comment]
Thanks @anthony-tuininga @cjbj for your response. I tried with the latest version of oracledb as well. Still I'm facing same issue. Unfortunately I cannot able to get the logs. I'll try to get the log. But it would be better if you could suggest any other way that I can try to connect to the oracle.

**Comment by cjbj** [comment]
For anyone seeing this, please answer the previous questions and additionaly give details such as what OS Python is on?  What version of Python?  What DB version?  It is the DB in the cloud? Show how you installed.

**Comment by Gobi2511** [comment]
I'm using the following versions:
**OS:** Ubuntu 22.04.4 LTS
**Python:** 3.11.9
**python-oracledb:** 2.5.1
**Oracle DB:** 19.25.0.0.0
**Is Cloud:** No.

**Comment by cjbj** [comment]
Have you ever been able to connect to the DB from your client?  Can SQL*Plus connect?  Do you have network issues?

**Comment by Gobi2511** [comment]
No it is not connecting through SQL Plus. FYI, the password has @ symbol included.

**Comment by cjbj** [comment]
This works for me in both Thin & Thick modes:
```
un = 'cj2'
cs = 'localhost/orclpdb1'
pw = 'c@j2'
with oracledb.connect(user=un, password=pw, dsn=cs) as connection:
    print(f"Connected as {connection.username}")
    with connection.cursor() as cursor:
        sql = """select systimestamp from dual"""
        for (r,) in cursor.execute(sql):
            print(r)
```
It prints:
```
$ python t.py 
Connected as cj2
2024-12-16 06:53:29.232815
```

**Comment by Gobi2511** [comment]
Sure let me try this thanks.

**Comment by Gobi2511** [comment]
Thanks @cjbj @anthony-tuininga . This is not something with python-oracledb. It is related to the MTU configuration. We increased the MTU configuration and it is working now. Thanks for your support and help. I'm closing this.

**Comment by JoBoSo** [comment]
I had an issue with connect hanging when I tried to use config_dir to access tnsnames.ora. This was with oracledb 2.4.1 and python 3.12.8. When I upgraded to oracledb 2.5.1 it worked. It might be worth up- or down-grading oracledb if you're at a loss.
