### ISSUE TITLE
Enhance type hinting in the subscr module

### ISSUE THREAD

**Issue by troyswanson** [oracle/python-oracledb#54]
The `subscr` module defines classes related to CQN functionality. It would be really nice to see these classes fully decked out with type hints. Here are some ideas:

* `Message.queries` could return `List[MessageQuery]`
* `Message.tables` could return `List[MessageTable]`
* `MessageTable.rows` could return `List[MessageRow]`

These enhancements would make working with subscription message objects much easier. Since there are several rows of nesting involved with interacting with the actual rows, it's sometimes hard to keep track of where we are 💫 

Thanks for your consideration!

**Comment by anthony-tuininga** [comment]
This has been implemented and I went through the remaining code and looked for missing/invalid type hinting and corrected the ones I found. If you have any further ones that need implementing or enhancing, let me know! Thanks.

**Comment by anthony-tuininga** [comment]
Included in python-oracledb 1.1.1 which was just released.
