### ISSUE TITLE
DPY-3015: password verifier type 09X939 is not supported by python-oracledb in thin mode

### ISSUE THREAD

**Issue by kintaka0812** [oracle/python-oracledb#67]
Any clue about how to solve this issue without installing any client as there is no internet connection in the pc?

**Comment by anthony-tuininga** [comment]
Yes, take a look at issue #26. Specifically, you need to remove the database setting `sec_case_sensitive_logon` (or set it to the value `TRUE`). If you cannot do that you will have no choice but to use the thick driver (and you will need to download the instant client on another machine and copy it across using some other means than the Internet).

**Comment by kintaka0812** [comment]
Thanks! I guess I need to speak with the Oracle DBA for that right?

Otherwise I can install the suitable packages from here:
https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html

Do I have to save it in a specific location? The code I am using is the very basic one, I just enter the username, pw and dns st the connect command.

**Comment by sterlingpetersen** [comment]
Would this error have the same or similar solutions? If not, happy to open a separate issue, if helpful.

` DPY-3015: password verifier type 0x1e81 is not supported by python-oracledb in thin mode`
