### ISSUE TITLE
return object attributes as int if metadata says it can be expressed as int

### ISSUE THREAD

**Issue by leo-b** [oracle/python-oracledb#99]
Currently when fetching objects, scale and precision of numbers is not considered and `NUMBER` attributes are always returned as python `float`s, even if scale is 0 and the `NUMBER` could be better represented as `int`.

Please add the same logic for objects depending on metadata as used when [fetching numbers](https://python-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#fetch-data-types).

See also discussion https://github.com/oracle/python-oracledb/discussions/88

**Comment by anthony-tuininga** [comment]
I have pushed a patch that should implement this enhancement. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you.

**Comment by anthony-tuininga** [comment]
The patch has been included in version 2.0.0 which was just released.
